/**
* @license FireShot - Webpage Screenshots and Annotations
* Copyright (C) 2007-2024 Evgeny Vokilsus (contacts@getfireshot.com)
*/

!function(){try{var e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{},n=(new Error).stack;n&&(e._sentryDebugIds=e._sentryDebugIds||{},e._sentryDebugIds[n]="3caf151f-b821-53be-9645-5557a3a82a5c")}catch(e){}}();
(()=>{var c=o=>{function f(e){let t=e.getClientRects();return t.length?{x:t[0].x,y:t[0].y,width:t[0].width,height:t[0].height,clientLeft:e.clientLeft,clientTop:e.clientTop}:{x:0,y:0,width:0,height:0,clientLeft:0,clientTop:0}}function m(e){let t=e.getPropertyValue("overflow-x"),n=e.getPropertyValue("overflow-y");return e&&(n!="hidden"||t!="hidden")&&s(e)}function s(e){return e.getPropertyValue("display")!="none"&&e.getPropertyValue("visibility")!="hidden"}function g(e){let t="";["transform","-webkit-transform","-o-transform","-moz-transform"].forEach(i=>{if(t===""){let l=e.getPropertyValue(i).match(/matrix\((.+)\)/i);l&&l.length>1&&(t=l[1])}});let n=t.split(",");return n.length>=3?[parseFloat(n[0]),parseFloat(n[3])]:[1,1]}function w(e,t){let n=(i,l)=>{let a=[...i.querySelectorAll(l)],d=document.createNodeIterator(i,Node.ELEMENT_NODE),r;for(;r=d.nextNode();)r.shadowRoot&&a.push(...n(r.shadowRoot,l));return a};document.querySelectorAll("iframe[fsFrameId], frame[fsFrameId]").forEach(i=>{i.removeAttribute("fsFrameId")}),n(document,"frame,iframe").forEach(i=>{let l=f(i),a=t===0&&document.scrollingElement?document.scrollingElement.scrollWidth:window.innerWidth,d=t===0&&document.scrollingElement?document.scrollingElement.scrollHeight:window.innerHeight,r=t===0&&document.scrollingElement?document.scrollingElement.scrollLeft:0,y=t===0&&document.scrollingElement?document.scrollingElement.scrollTop:0,h=document.defaultView.getComputedStyle(i,""),p=l.x+l.clientLeft+r>=0&&l.x+l.width<=a+1&&l.width<=window.innerWidth+1&&l.y+l.clientTop+y>=0&&l.y+l.height<=d+1&&l.height<=window.innerHeight+1&&s(h);l.x+=e.clientLeft+e.x,l.y+=e.clientTop+e.y;let x=g(h),u=t+"-"+(document.querySelectorAll("iframe[fsFrameId], frame[fsFrameId]").length+1);i.setAttribute("fsFrameId",u),i.contentWindow.postMessage({message:"rInfo",exts:l,scales:x,selectorId:u,fullyVisible:p,scrollingAttr:i.getAttribute("scrolling"),level:t+1},"*")})}if(!o.data||typeof o.data.message>"u")return!1;switch(o.data.message){case"rInfo":{window.removeEventListener("message",c);let e=document.scrollingElement||document.body,t=location.href.match(/chat\.google\.com\/u/)&&o.data.scrollingAttr==="no"&&o.data.exts.width>200,n={level:o.data.level,selectorId:o.data.selectorId,x:o.data.exts.x,y:o.data.exts.y,width:o.data.exts.width,height:o.data.exts.height,scales:o.data.scales,clientLeft:o.data.exts.clientLeft,clientTop:o.data.exts.clientTop,clientWidth:window.innerWidth,clientHeight:window.innerHeight,scrollWidth:e.scrollWidth,scrollHeight:e.scrollHeight,scrollable:document.body&&m(document.defaultView.getComputedStyle(document.body,""))||t,fullyVisible:o.data.fullyVisible};chrome.runtime.sendMessage({message:"frameInfo",data:n}),w(n,o.data.level)}break}};window.addEventListener("message",c,!1);setTimeout(()=>window.removeEventListener("message",c),2e3);})();
//# sourceMappingURL=fsFrames.js.map

//# debugId=3caf151f-b821-53be-9645-5557a3a82a5c
